// src/pages/Home.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { tmdbService, getBackdropUrl, getPosterUrl } from "../services/tmdb";
  import type { Movie, TVShow } from "../types";
  import SectionCarousel from "../components/SectionCarousel.svelte";
  import Hero from "../components/Hero.svelte";
  import ContinueWatching from "../components/ContinueWatching.svelte";
  import { link } from "svelte-spa-router";

  let loading = true;

  type Item = {
    id: number;
    title: string;
    posterPath: string | null;
    href: string;
    meta?: string | null;
  };

  const platforms = [
    "Netflix",
    "Prime",
    "Max",
    "Star+",
    "Disney+",
    "Paramount+",
    "Apple Tv",
  ];

  let trendingMovies: Item[] = [];
  let trendingTV: Item[] = [];
  let topRatedMovies: Item[] = [];
  let topRatedTV: Item[] = [];
  let popularMovies: Item[] = [];
  let popularTV: Item[] = [];
  let actionMovies: Item[] = [];
  let comedyMovies: Item[] = [];
  let dramaMovies: Item[] = [];
  let horrorMovies: Item[] = [];
  let romanceMovies: Item[] = [];
  let sciFiMovies: Item[] = [];
  let documentaries: Item[] = [];
  let animationMovies: Item[] = [];

  let heroItems: any[] = [];

  const mapMovies = (items: Movie[]): Item[] =>
    items.map((m) => ({
      id: m.id,
      title: m.title,
      posterPath: m.poster_path,
      href: `/movie/${m.id}`,
      meta: m.release_date ? m.release_date.slice(0, 4) : null,
    }));

  const mapTV = (items: TVShow[]): Item[] =>
    items.map((t) => ({
      id: t.id,
      title: t.name,
      posterPath: t.poster_path,
      href: `/tv/${t.id}`,
      meta: t.first_air_date ? t.first_air_date.slice(0, 4) : null,
    }));

  onMount(async () => {
    loading = true;
    try {
      const [
        trendingMoviesRes,
        trendingTVRes,
        topRatedMoviesRes,
        topRatedTVRes,
        popularMoviesRes,
        popularTVRes,
        actionRes,
        comedyRes,
        dramaRes,
        horrorRes,
        romanceRes,
        sciFiRes,
        docRes,
        animationRes,
        trendingAllRes,
      ] = await Promise.all([
        tmdbService.getTrendingMovies("week"),
        tmdbService.getTrendingTVShows("week"),
        tmdbService.getTopRatedMovies(1),
        tmdbService.getTopRatedTVShows(1),
        tmdbService.getPopularMovies(1),
        tmdbService.getPopularTVShows(1),
        tmdbService.discoverMovies(1, { genre: 28 }),
        tmdbService.discoverMovies(1, { genre: 35 }),
        tmdbService.discoverMovies(1, { genre: 18 }),
        tmdbService.discoverMovies(1, { genre: 27 }),
        tmdbService.discoverMovies(1, { genre: 10749 }),
        tmdbService.discoverMovies(1, { genre: 878 }),
        tmdbService.discoverMovies(1, { genre: 99 }),
        tmdbService.discoverMovies(1, { genre: 16 }),
        tmdbService.getTrendingAll("week"),
      ]);

      trendingMovies = mapMovies(trendingMoviesRes.results);
      trendingTV = mapTV(trendingTVRes.results);
      topRatedMovies = mapMovies(topRatedMoviesRes.results);
      topRatedTV = mapTV(topRatedTVRes.results);
      popularMovies = mapMovies(popularMoviesRes.results);
      popularTV = mapTV(popularTVRes.results);
      actionMovies = mapMovies(actionRes.results);
      comedyMovies = mapMovies(comedyRes.results);
      dramaMovies = mapMovies(dramaRes.results);
      horrorMovies = mapMovies(horrorRes.results);
      romanceMovies = mapMovies(romanceRes.results);
      sciFiMovies = mapMovies(sciFiRes.results);
      documentaries = mapMovies(docRes.results);
      animationMovies = mapMovies(animationRes.results);

      const mixed = trendingAllRes.results;
      heroItems = mixed
        .filter(
          (x: any) =>
            (x?.backdrop_path || x?.poster_path) && (x?.title || x?.name),
        )
        .slice(0, 10)
        .map((x: any) => {
          const isMovie = Boolean(x.title);
          return {
            id: x.id,
            type: isMovie ? "movie" : "tv",
            title: isMovie ? x.title : x.name,
            backdropPath: x.backdrop_path ?? null,
            posterPath: x.poster_path ?? null,
            meta: isMovie
              ? x.release_date
                ? String(x.release_date).slice(0, 4)
                : null
              : x.first_air_date
                ? String(x.first_air_date).slice(0, 4)
                : null,
          };
        });
    } finally {
      loading = false;
    }
  });
</script>

<section class="space-y-10 pb-6">
  {#if loading}
    <div
      class="flex h-[400px] items-center justify-center rounded-3xl bg-zinc-900/50"
    >
      <div class="flex flex-col items-center gap-4">
        <div
          class="h-10 w-10 animate-spin rounded-full border-4 border-yellow-400/30 border-t-yellow-400"
        ></div>
        <p class="text-sm text-white/50">Loading content...</p>
      </div>
    </div>
  {:else if heroItems.length}
    <Hero items={heroItems} />
  {/if}

  <ContinueWatching />

  <SectionCarousel title="Trending Movies" items={trendingMovies} {loading} />
  <SectionCarousel title="Trending TV Shows" items={trendingTV} {loading} />
  <SectionCarousel title="Top Rated Movies" items={topRatedMovies} {loading} />
  <SectionCarousel title="Top Rated TV Shows" items={topRatedTV} {loading} />
  <SectionCarousel title="Popular Movies" items={popularMovies} {loading} />
  <SectionCarousel title="Popular TV Shows" items={popularTV} {loading} />
  <SectionCarousel title="Action Movies" items={actionMovies} {loading} />
  <SectionCarousel title="Comedy Movies" items={comedyMovies} {loading} />
  <SectionCarousel title="Drama Movies" items={dramaMovies} {loading} />
  <SectionCarousel title="Horror Movies" items={horrorMovies} {loading} />
  <SectionCarousel title="Romance Movies" items={romanceMovies} {loading} />
  <SectionCarousel title="Sci-Fi Movies" items={sciFiMovies} {loading} />
  <SectionCarousel title="Documentaries" items={documentaries} {loading} />
  <SectionCarousel title="Animation Movies" items={animationMovies} {loading} />
</section>

// src/pages/Home.tsx
import { useState, useEffect } from 'react';
import Hero from '../components/Hero';
import MediaRow from '../components/MediaRow';
import ContinueWatching from '../components/ContinueWatching';
import type { Movie, TVShow } from '../types';
import { tmdbService } from '../services/tmdb';
import './Home.css';

const Home = () => {
  const [trendingMovies, setTrendingMovies] = useState<Movie[]>([]);
  const [trendingTVShows, setTrendingTVShows] = useState<TVShow[]>([]);
  const [popularMovies, setPopularMovies] = useState<Movie[]>([]);
  const [popularTVShows, setPopularTVShows] = useState<TVShow[]>([]);
  const [topRatedMovies, setTopRatedMovies] = useState<Movie[]>([]);
  const [topRatedTVShows, setTopRatedTVShows] = useState<TVShow[]>([]);
  const [actionMovies, setActionMovies] = useState<Movie[]>([]);
  const [comedyMovies, setComedyMovies] = useState<Movie[]>([]);
  const [dramaMovies, setDramaMovies] = useState<Movie[]>([]);
  const [horrorMovies, setHorrorMovies] = useState<Movie[]>([]);
  const [romanceMovies, setRomanceMovies] = useState<Movie[]>([]);
  const [sciFiMovies, setSciFiMovies] = useState<Movie[]>([]);
  const [documentaries, setDocumentaries] = useState<Movie[]>([]);
  const [animationMovies, setAnimationMovies] = useState<Movie[]>([]);
  const [heroItems, setHeroItems] = useState<(Movie | TVShow)[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setError(null);

        // Fetch all data in parallel
        const [
          trendingAllResponse,
          trendingMoviesResponse,
          trendingTVResponse,
          popularMoviesResponse,
          popularTVResponse,
          topRatedMoviesResponse,
          topRatedTVResponse,
          actionMoviesResponse,
          comedyMoviesResponse,
          dramaMoviesResponse,
          horrorMoviesResponse,
          romanceMoviesResponse,
          sciFiMoviesResponse,
          documentariesResponse,
          animationMoviesResponse
        ] = await Promise.all([
          tmdbService.getTrendingAll('week'),
          tmdbService.getTrendingMovies('week'),
          tmdbService.getTrendingTVShows('week'),
          tmdbService.getPopularMovies(),
          tmdbService.getPopularTVShows(),
          tmdbService.getTopRatedMovies(),
          tmdbService.getTopRatedTVShows(),
          tmdbService.getPopularMovies(1),
          tmdbService.getPopularMovies(2),
          tmdbService.getPopularMovies(3),
          tmdbService.getTopRatedMovies(1),
          tmdbService.getTopRatedMovies(2),
          tmdbService.getNowPlayingMovies(),
          tmdbService.getUpcomingMovies(),
          tmdbService.getPopularMovies(4)
        ]);

        // Set hero items (mix of trending movies and TV shows only; exclude people)
        const heroContent = trendingAllResponse.results
          .filter((r: any) => r.media_type === 'movie' || r.media_type === 'tv')
          .slice(0, 5);
        setHeroItems(heroContent);

        setTrendingMovies(trendingMoviesResponse.results.slice(0, 12));
        setTrendingTVShows(trendingTVResponse.results.slice(0, 12));
        setPopularMovies(popularMoviesResponse.results.slice(0, 12));
        setPopularTVShows(popularTVResponse.results.slice(0, 12));
        setTopRatedMovies(topRatedMoviesResponse.results.slice(0, 12));
        setTopRatedTVShows(topRatedTVResponse.results.slice(0, 12));
        
        // Set genre-specific movies
        setActionMovies(actionMoviesResponse.results.slice(0, 12));
        setComedyMovies(comedyMoviesResponse.results.slice(0, 12));
        setDramaMovies(dramaMoviesResponse.results.slice(0, 12));
        setHorrorMovies(horrorMoviesResponse.results.slice(0, 12));
        setRomanceMovies(romanceMoviesResponse.results.slice(0, 12));
        setSciFiMovies(sciFiMoviesResponse.results.slice(0, 12));
        setDocumentaries(documentariesResponse.results.slice(0, 12));
        setAnimationMovies(animationMoviesResponse.results.slice(0, 12));
      } catch (err) {
        console.error('Error fetching data:', err);
        setError('Failed to load content. Please try again later.');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  if (error) {
    return (
      <div className="home-error">
        <div className="error-content">
          <h2>Oops! Something went wrong</h2>
          <p>{error}</p>
          <button onClick={() => window.location.reload()} className="btn btn-primary">
            Try Again
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="home">
      {/* Hero Section */}
      {heroItems.length > 0 && (
        <Hero items={heroItems} />
      )}

      {/* Continue Watching */}
      <ContinueWatching />

      {/* Content Sections */}
      <div className="home-content">
        {/* Content Categories */}
        <MediaRow
          items={trendingMovies}
          type="movie"
          title="Trending Movies"
          loading={loading}
          category="trending"
        />

        <MediaRow
          items={trendingTVShows}
          type="tv"
          title="Trending TV Shows"
          loading={loading}
          category="trending"
        />

        <MediaRow
          items={topRatedMovies}
          type="movie"
          title="Top Rated Movies"
          loading={loading}
          category="top-rated"
        />

        <MediaRow
          items={topRatedTVShows}
          type="tv"
          title="Top Rated TV Shows"
          loading={loading}
          category="top-rated"
        />

        <MediaRow
          items={popularMovies}
          type="movie"
          title="Popular Movies"
          loading={loading}
          category="popular"
        />

        <MediaRow
          items={popularTVShows}
          type="tv"
          title="Popular TV Shows"
          loading={loading}
          category="popular"
        />

        <MediaRow
          items={actionMovies}
          type="movie"
          title="Action Movies"
          loading={loading}
          category="action"
        />

        <MediaRow
          items={comedyMovies}
          type="movie"
          title="Comedy Movies"
          loading={loading}
          category="comedy"
        />

        <MediaRow
          items={dramaMovies}
          type="movie"
          title="Drama Movies"
          loading={loading}
          category="drama"
        />

        <MediaRow
          items={horrorMovies}
          type="movie"
          title="Horror Movies"
          loading={loading}
          category="horror"
        />

        <MediaRow
          items={romanceMovies}
          type="movie"
          title="Romance Movies"
          loading={loading}
          category="romance"
        />

        <MediaRow
          items={sciFiMovies}
          type="movie"
          title="Sci-Fi Movies"
          loading={loading}
          category="sci-fi"
        />

        <MediaRow
          items={documentaries}
          type="movie"
          title="Documentaries"
          loading={loading}
          category="documentaries"
        />

        <MediaRow
          items={animationMovies}
          type="movie"
          title="Animation Movies"
          loading={loading}
          category="animation"
        />
      </div>
    </div>
  );
};

export default Home;
