// src/components/ContinueWatching.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { link } from "svelte-spa-router";
  import { supabase, isSupabaseEnabled } from "../lib/supabaseClient";
  import {
    watchHistoryService,
    type WatchHistoryItem,
  } from "../services/watchHistory";
  import { getPosterUrl } from "../services/tmdb";
  import { redirectToLogin } from "../lib/loginRedirect";
  import { isPlayerServerKey } from "../services/playerServers";
  import { Play, X, ChevronLeft, ChevronRight, Trash2 } from "lucide-svelte";

  let loading = true;
  let error: string | null = null;
  let userId: string | null = null;
  let needsLogin = false;

  type Item = {
    id: number;
    title: string;
    posterPath: string | null;
    href: string;
    progress: number;
    type: "movie" | "tv";
    season?: number;
    episode?: number;
    meta?: string | null;
  };

  let items: Item[] = [];
  let scroller: HTMLDivElement | null = null;

  const scrollByAmount = (dir: -1 | 1) => {
    if (!scroller) return;
    scroller.scrollBy({ left: dir * 480, behavior: "smooth" });
  };

  const removeItem = async (item: Item) => {
    if (!userId) return;
    try {
      await watchHistoryService.remove(
        userId,
        item.id,
        item.type,
        item.season,
        item.episode,
      );
      items = items.filter((i) => i.id !== item.id || i.type !== item.type);
    } catch (e) {
      console.error("Failed to remove item", e);
    }
  };

  const PER_TITLE_SERVER_PREFIX = "streame:lastServer";

  const readLastServerFor = (it: WatchHistoryItem) => {
    try {
      const baseKey =
        it.type === "tv"
          ? `${PER_TITLE_SERVER_PREFIX}:${it.type}:${it.tmdb_id}:${it.season_number ?? 1}:${it.episode_number ?? 1}`
          : `${PER_TITLE_SERVER_PREFIX}:${it.type}:${it.tmdb_id}`;

      const v = localStorage.getItem(baseKey);
      return v && isPlayerServerKey(v) ? v : null;
    } catch {
      return null;
    }
  };

  const toHref = (it: WatchHistoryItem) => {
    const startAt =
      it.last_position && it.last_position > 0
        ? Math.floor(it.last_position)
        : 0;
    const server = readLastServerFor(it);
    const serverQuery = server ? `?server=${encodeURIComponent(server)}` : "";

    if (it.type === "movie") {
      return startAt > 0
        ? `/watch/movie/${it.tmdb_id}/${startAt}${serverQuery}`
        : `/watch/movie/${it.tmdb_id}${serverQuery}`;
    }

    const s = it.season_number ?? 1;
    const e = it.episode_number ?? 1;
    return startAt > 0
      ? `/watch/tv/${it.tmdb_id}/${s}/${e}/${startAt}${serverQuery}`
      : `/watch/tv/${it.tmdb_id}/${s}/${e}${serverQuery}`;
  };

  const dedupeLatest = (history: WatchHistoryItem[]) => {
    const filtered = history.filter((h) => h.progress > 0 && h.progress < 100);

    const latestMap = new Map<string, WatchHistoryItem>();
    for (const h of filtered) {
      const key = `${h.type}-${h.tmdb_id}`;
      const existing = latestMap.get(key);
      if (!existing) {
        latestMap.set(key, h);
        continue;
      }
      if (
        new Date(h.last_watched).getTime() >
        new Date(existing.last_watched).getTime()
      ) {
        latestMap.set(key, h);
      }
    }

    return Array.from(latestMap.values()).sort(
      (a, b) =>
        new Date(b.last_watched).getTime() - new Date(a.last_watched).getTime(),
    );
  };

  const load = async () => {
    loading = true;
    error = null;
    needsLogin = false;

    try {
      if (!isSupabaseEnabled) {
        userId = null;
        items = [];
        return;
      }

      const { data } = await supabase.auth.getUser();
      userId = data?.user?.id ?? null;

      if (!userId) {
        needsLogin = true;
        items = [];
        return;
      }

      const history = await watchHistoryService.list(userId, 20);
      const deduped = dedupeLatest(history);

      items = deduped.slice(0, 10).map((h) => ({
        id: h.tmdb_id,
        title: h.title,
        posterPath: h.poster_path,
        href: toHref(h),
        progress: h.progress || 0,
        type: h.type,
        season: h.season_number,
        episode: h.episode_number,
        meta:
          h.type === "tv"
            ? `S${h.season_number ?? 1} E${h.episode_number ?? 1}`
            : null,
      }));
    } catch (e: any) {
      console.error("Failed to load Continue Watching", e);
      error = e?.message ?? "Failed to load Continue Watching";
      items = [];
    } finally {
      loading = false;
    }
  };

  onMount(() => {
    load();
  });
</script>

{#if error}
  <div
    class="rounded-2xl border border-red-500/20 bg-red-500/10 p-5 text-sm text-red-200"
  >
    {error}
  </div>
{:else if !loading && needsLogin}
  <div class="rounded-2xl border border-white/10 bg-white/5 p-5">
    <div
      class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"
    >
      <div>
        <div class="text-sm font-semibold">Continue Watching</div>
        <div class="mt-1 text-xs text-white/60">
          Sign in to see your synced watch history.
        </div>
      </div>
      <button
        class="inline-flex h-10 items-center justify-center rounded-xl bg-yellow-400 px-4 text-xs font-black text-black transition-all hover:bg-yellow-300 active:scale-95"
        on:click={() => redirectToLogin(window.location.hash || "#/")}
      >
        Sign in
      </button>
    </div>
  </div>
{:else if !loading && items.length > 0}
  <section class="space-y-4">
    <div class="flex items-center justify-between">
      <h2 class="text-lg font-bold text-white">Continue Watching</h2>
      <div class="flex items-center gap-2">
        <button
          class="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white/5 ring-1 ring-white/10 hover:bg-white/10 transition-colors"
          on:click={() => scrollByAmount(-1)}
          aria-label="Scroll left"
        >
          <ChevronLeft size={18} />
        </button>
        <button
          class="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white/5 ring-1 ring-white/10 hover:bg-white/10 transition-colors"
          on:click={() => scrollByAmount(1)}
          aria-label="Scroll right"
        >
          <ChevronRight size={18} />
        </button>
      </div>
    </div>

    <div
      bind:this={scroller}
      class="no-scrollbar flex gap-4 overflow-x-auto pb-2 scroll-smooth"
    >
      {#each items as item (item.id + item.type)}
        <div class="group relative flex-shrink-0 w-[200px] sm:w-[240px]">
          <a
            use:link
            href={item.href}
            class="block overflow-hidden rounded-2xl bg-zinc-900 ring-1 ring-white/10 transition-all duration-200 hover:ring-yellow-400/50 hover:scale-[1.02]"
          >
            <!-- Poster -->
            <div class="relative aspect-video overflow-hidden">
              <img
                src={getPosterUrl(item.posterPath, "w500")}
                alt={item.title}
                class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                loading="lazy"
              />

              <!-- Play Overlay -->
              <div
                class="absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 transition-opacity group-hover:opacity-100"
              >
                <div
                  class="flex h-14 w-14 items-center justify-center rounded-full bg-yellow-400 shadow-lg shadow-yellow-400/30"
                >
                  <Play size={24} class="text-black" fill="currentColor" />
                </div>
              </div>

              <!-- Progress Bar -->
              <div class="absolute bottom-0 left-0 right-0 h-1 bg-black/60">
                <div
                  class="h-full bg-yellow-400 transition-all duration-300"
                  style="width: {item.progress}%"
                ></div>
              </div>
            </div>

            <!-- Info -->
            <div class="p-3">
              <h3 class="line-clamp-1 text-sm font-semibold text-white">
                {item.title}
              </h3>
              <div class="mt-1 flex items-center gap-2">
                {#if item.meta}
                  <span class="text-xs text-white/60">{item.meta}</span>
                  <span class="text-white/30">•</span>
                {/if}
                <span class="text-xs text-yellow-400"
                  >{Math.round(item.progress)}% watched</span
                >
              </div>
            </div>
          </a>

          <!-- Delete Button -->
          <button
            on:click|preventDefault={() => removeItem(item)}
            class="absolute right-2 top-2 z-10 flex h-8 w-8 items-center justify-center rounded-full bg-black/60 text-white/70 opacity-0 backdrop-blur-md transition-all hover:bg-red-500 hover:text-white group-hover:opacity-100"
            title="Remove from history"
          >
            <Trash2 size={14} />
          </button>
        </div>
      {/each}
    </div>
  </section>
{/if}

// src/components/ContinueWatching.tsx
import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Play, Clock, AlertCircle, X, CircleChevronLeft, CircleChevronRight, Trash2, SlidersHorizontal, Check } from 'lucide-react';
import { watchHistoryService, type WatchHistoryItem } from '../services/watchHistory';
import { getPosterUrl } from '../services/tmdb';
import { useAuth } from '../context/AuthContext';
import { formatDuration } from '../utils/formatDuration';
import './ContinueWatching.css';

type SortOption = 'recent' | 'progress' | 'title';
type FilterOption = 'all' | 'movies' | 'tv';

const ContinueWatching = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [items, setItems] = useState<WatchHistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<SortOption>('recent');
  const [filterBy, setFilterBy] = useState<FilterOption>('all');
  const [showOptions, setShowOptions] = useState(false);
  const rowRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (user) {
      loadHistory();
    } else {
      setItems([]);
      setLoading(false);
    }
  }, [user]);

  const loadHistory = async () => {
    if (!user) return;
    try {
      setLoading(true);
      setError(null);
      const history = await watchHistoryService.list(user.id, 20);
      // Keep anything that has been started but not fully completed
      const filtered = history.filter(item => item.progress > 0 && item.progress < 100);

      // Deduplicate: for TV, keep latest episode per show; for movies, keep latest entry
      const latestMap = new Map<string, WatchHistoryItem>();
      filtered.forEach(item => {
        const key = `${item.type}-${item.tmdb_id}`;
        const existing = latestMap.get(key);
        if (!existing) {
          latestMap.set(key, item);
          return;
        }
        if (new Date(item.last_watched).getTime() > new Date(existing.last_watched).getTime()) {
          latestMap.set(key, item);
        }
      });

      const deduped = Array.from(latestMap.values()).sort(
        (a, b) => new Date(b.last_watched).getTime() - new Date(a.last_watched).getTime()
      );

      setItems(deduped.slice(0, 10));
    } catch (err) {
      console.error('Failed to load watch history:', err);
      setError('Failed to load your watch history. Please try again later.');
      setItems([]);
    } finally {
      setLoading(false);
    }
  };

  const handleItemClick = (item: WatchHistoryItem) => {
    const startAt = item.last_position && item.last_position > 0
      ? `?startAt=${Math.floor(item.last_position)}`
      : '';

    if (item.type === 'movie') {
      navigate(`/watch/movie/${item.tmdb_id}${startAt}`);
    } else {
      navigate(`/watch/tv/${item.tmdb_id}/season/${item.season_number}/episode/${item.episode_number}${startAt}`);
    }
  };

  const handleDelete = async (item: WatchHistoryItem) => {
    if (!user) return;
    try {
      await watchHistoryService.remove(
        user.id,
        item.tmdb_id,
        item.type,
        item.season_number,
        item.episode_number
      );
      setItems(prev => prev.filter(i =>
        !(
          i.tmdb_id === item.tmdb_id &&
          i.type === item.type &&
          i.season_number === item.season_number &&
          i.episode_number === item.episode_number
        )
      ));
    } catch (err) {
      console.error('Failed to delete watch history item', err);
      setError('Failed to delete item. Please try again.');
    }
  };

  const handleClearAll = async () => {
    if (!user || !window.confirm('Are you sure you want to clear all watch history?')) return;
    try {
      await watchHistoryService.clear(user.id);
      setItems([]);
    } catch (err) {
      console.error('Failed to clear watch history:', err);
      setError('Failed to clear history. Please try again.');
    }
  };

  const getSortedAndFilteredItems = () => {
    let filtered = [...items];
    
    if (filterBy === 'movies') {
      filtered = filtered.filter(item => item.type === 'movie');
    } else if (filterBy === 'tv') {
      filtered = filtered.filter(item => item.type === 'tv');
    }
    
    filtered.sort((a, b) => {
      switch (sortBy) {
        case 'progress':
          return b.progress - a.progress;
        case 'title':
          return a.title.localeCompare(b.title);
        case 'recent':
        default:
          return new Date(b.last_watched).getTime() - new Date(a.last_watched).getTime();
      }
    });
    
    return filtered;
  };

  if (!user) {
    return null;
  }

  if (loading) {
    return (
      <div className="continue-watching">
        <div className="continue-watching-header">
          <h2>Continue Watching</h2>
          <Clock size={20} />
        </div>
        <div className="continue-watching-grid">
          {[1, 2, 3, 4, 5].map((i) => (
            <div key={i} className="continue-watching-skeleton">
              <div className="skeleton-poster" />
              <div className="skeleton-info">
                <div className="skeleton-title" />
                <div className="skeleton-meta" />
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="continue-watching">
        <div className="continue-watching-header">
          <h2>Continue Watching</h2>
          <Clock size={20} />
        </div>
        <div className="continue-watching-error">
          <AlertCircle size={32} />
          <p>{error}</p>
          <button onClick={loadHistory} className="retry-button">
            Try Again
          </button>
        </div>
      </div>
    );
  }

  const scrollRow = (direction: 'left' | 'right') => {
    const el = rowRef.current;
    if (!el) return;
    const cardWidth = 176; // card width (160px) + gap (16px)
    const amount = cardWidth * 3;
    el.scrollBy({ left: direction === 'left' ? -amount : amount, behavior: 'smooth' });
  };

  const displayItems = getSortedAndFilteredItems();

  if (items.length === 0) {
    return null;
  }

  return (
    <div className="continue-watching">
      <div className="continue-watching-header">
        <div className="cw-header-left">
          <h2>Continue Watching</h2>
          <Clock size={20} />
          <span className="cw-count">{displayItems.length} {displayItems.length === 1 ? 'item' : 'items'}</span>
        </div>
        <div className="cw-header-actions">
          <button 
            className="cw-options-btn"
            onClick={() => setShowOptions(!showOptions)}
            aria-label="Filter and sort options"
          >
            <SlidersHorizontal size={18} />
          </button>
          {items.length > 0 && (
            <button 
              className="cw-clear-btn"
              onClick={handleClearAll}
              aria-label="Clear all"
            >
              <Trash2 size={18} />
              <span>Clear All</span>
            </button>
          )}
        </div>
      </div>
      {showOptions && (
        <div className="cw-options-panel">
          <div className="cw-option-group">
            <label>Filter:</label>
            <div className="cw-option-buttons">
              <button 
                className={filterBy === 'all' ? 'active' : ''}
                onClick={() => setFilterBy('all')}
              >
                {filterBy === 'all' && <Check size={14} />}
                All
              </button>
              <button 
                className={filterBy === 'movies' ? 'active' : ''}
                onClick={() => setFilterBy('movies')}
              >
                {filterBy === 'movies' && <Check size={14} />}
                Movies
              </button>
              <button 
                className={filterBy === 'tv' ? 'active' : ''}
                onClick={() => setFilterBy('tv')}
              >
                {filterBy === 'tv' && <Check size={14} />}
                TV Shows
              </button>
            </div>
          </div>
          <div className="cw-option-group">
            <label>Sort by:</label>
            <div className="cw-option-buttons">
              <button 
                className={sortBy === 'recent' ? 'active' : ''}
                onClick={() => setSortBy('recent')}
              >
                {sortBy === 'recent' && <Check size={14} />}
                Recently Watched
              </button>
              <button 
                className={sortBy === 'progress' ? 'active' : ''}
                onClick={() => setSortBy('progress')}
              >
                {sortBy === 'progress' && <Check size={14} />}
                Progress
              </button>
              <button 
                className={sortBy === 'title' ? 'active' : ''}
                onClick={() => setSortBy('title')}
              >
                {sortBy === 'title' && <Check size={14} />}
                Title
              </button>
            </div>
          </div>
        </div>
      )}
      {displayItems.length === 0 ? (
        <div className="continue-watching-empty">
          <AlertCircle size={48} />
          <p>No items match your current filters.</p>
          <button 
            onClick={() => {
              setFilterBy('all');
              setSortBy('recent');
            }}
            className="reset-filters-btn"
          >
            Reset Filters
          </button>
        </div>
      ) : (
        <div className="continue-watching-row">
          <button className="cw-arrow left" aria-label="Scroll left" onClick={() => scrollRow('left')}>
            <CircleChevronLeft size={20} />
          </button>
          <div className="continue-watching-track" ref={rowRef}>
            {displayItems.map((item) => (
            <div
              key={`${item.tmdb_id}-${item.type}-${item.season_number}-${item.episode_number}`}
              className="continue-watching-card"
              onClick={() => handleItemClick(item)}
            >
              <button
                className="cw-delete"
                aria-label="Remove from Continue Watching"
                onClick={(e) => {
                  e.stopPropagation();
                  handleDelete(item);
                }}
              >
                <X size={16} />
              </button>
              <div className="continue-watching-poster">
                <img 
                  src={getPosterUrl(item.poster_path)} 
                  alt={item.title}
                  loading="lazy"
                  onError={(e) => {
                    e.currentTarget.src = 'https://via.placeholder.com/300x450/1a1a1a/666666?text=No+Image';
                  }}
                />
                <div className="continue-watching-overlay">
                  <Play size={48} fill="currentColor" />
                </div>
                <div className="continue-watching-progress">
                  <div
                    className="continue-watching-progress-bar"
                    style={{ width: `${item.progress}%` }}
                  />
                </div>
              </div>
              <div className="continue-watching-info">
                <h3>{item.title}</h3>
                {item.type === 'tv' && (
                  <p className="continue-watching-episode">
                    S{item.season_number} E{item.episode_number}
                  </p>
                )}
                {item.last_position && item.last_position > 0 && (
                  <p className="continue-watching-timestamp">
                    ⏱️ {formatDuration(item.last_position)}
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>
        <button className="cw-arrow right" aria-label="Scroll right" onClick={() => scrollRow('right')}>
          <CircleChevronRight size={20} />
        </button>
      </div>
      )}
    </div>
  );
};

export default ContinueWatching;
